- src/App.js
- src/components/common/CommonButtons/CommonButtons.style.js
- src/components/common/NavigatonBar.jsx
- src/index.js
- src/pages/About/AboutPage.jsx
- src/pages/Activity/ActivityPage.jsx
- src/pages/Admin/ActivityPage.jsx
- src/pages/Admin/ClassInfoPage.jsx
- src/pages/Admin/EPRiansPage.jsx
- src/pages/Admin/LoginPage.jsx
- src/pages/Admin/RecruitmentPage.jsx
- src/pages/Contact/ContactPage.jsx
- src/pages/EPRians/EPRiansPage.jsx
- src/pages/Joinus/JoinusPage.jsx
- src/pages/LayoutPage.jsx
- src/pages/Main/MainPage.jsx
- src/styles/font.js
- src/styles/global.css
- 이슈 번호 작성 #7 
- 기본 라우팅 설정 및 푸터 포함한 레이아웃 파일 생성
네비바도 layoutpage에 포함시키려 했는데 메인 페이지의 경우 그렇게 하면 색 반영이 안 될 거 같아 푸터만 포함시켰습니다
각자 페이지 작업할 때 import 해서 사용해주세요~
문제없는지 확인해주세요~~
> 라우팅 기본 설정을 한다.

- package-lock.json
- package.json
- src/api/example.js
- src/api/index.js
> axios 인스턴스를 생성한다.

- src/api/fileUpload.js
- src/api/logo.js
- src/api/member.js
- src/api/recruitment.js
- src/components/common/UploadComponent/UploadComponent.jsx
- src/pages/Admin/EPRiansPage.jsx
- 이슈 번호 작성 #25 
- Presigned Url로 이미지 업로드 컴포넌트를 만든다.
이미지를 서버에 업로드 할 때 그대로 사용하시면 되는 부분은
fileUpload.js에 있는 함수와 ImageUploadComponent.js 입니다.
presigned url을 이용해 프론트에서 바로 s3로 이미지를 업로드하는 방식입니다.
1. 이미지 파일명을 백엔드에 보내서 presigned url 발급 (postPresignedURL)
2. 발급된 url에 이미지 저장 (putPresignedURL)
3. 이미지 저장 후 쿼리파라미터를 제외한 url을 백엔드에 전송 (post 함수 구현해주셔야합니다!)
업로드 컴포넌트를 임포트한 페이지에 해당 state를 생성해주세요.
생성한 state들을 업로드 컴포넌트에 전달해주세요.
업로드 컴포넌트를 임포트한 페이지에 기존 이미지를 불러오는 함수와
저장버튼을 클릭하였을 때 presigned url를 post해주는 함수를 작성해주시면 됩니다.
Admin/EPRians 페이지에 예시 코드를 적어놓았으니 참고해주세요!!
> Presigned Url로 이미지 업로드 컴포넌트를 만든다.

- src/App.js
- src/api/award.js
- src/api/corporate.js
- src/api/index.js
- src/api/login.js
- src/api/network.js
- src/api/project.js
- src/api/session.js
- src/components/activities-admin/AdminActivityItem.style.js
- src/components/activities-admin/AwardStatistics.jsx
- src/components/activities-admin/CorporateProject.jsx
- src/components/activities-admin/Network.jsx
- src/components/activities-admin/ProjectItem.jsx
- src/components/activities-admin/ProjectList.jsx
- src/components/activities-admin/SessionList.jsx
- src/components/activities-admin/UploadItem.jsx
- src/components/activities/ActivityCard.jsx
- src/components/activities/CorporateCard.jsx
- src/components/common/NavigatonBar.jsx
- src/components/common/UploadComponent/UploadComponent.jsx
- src/hooks/useResizeTextarea.js
- src/hooks/useScrollFadeIn.js
- src/pages/Activity/ActivityPage.jsx
- src/pages/Admin/ActivityPage.jsx
- src/pages/Admin/LoginPage.jsx
- src/pages/PrivateRouter.jsx
- src/styles/global.css
- #27 
- #28 
- #29 
https://github.com/user-attachments/assets/5b903c36-06ad-43b9-b250-1d38f0a5a85a
https://github.com/user-attachments/assets/0ae4a44c-9da3-4abb-9e2c-45a788e053a9
> activities 페이지, admin-activities 페이지에 api 연결을 한다.

- src/api/classinfo.js
- src/components/About/CardContent.jsx
- src/components/About/DepartmentCard.jsx
- src/components/common/NavigatonBar.style.js
- src/pages/About/AboutPage.jsx
- src/pages/About/AboutPage.style.js
- src/pages/Admin/ClassInfoPage.jsx
- src/pages/Contact/ContactPage.jsx
- src/pages/Contact/ContactPage.style.js
- #38 #39 #40 #41
- Contact 페이지에 api를 연결한다.
- admin_class info 페이지에 api를 연결한다.
- About, Contact 페이지에 애니메이션을 적용한다.
> Contact, admin_class info 페이지에 api를 연결한다.

- src/assets/arrow_right.svg
- src/components/EPRians-admin/MemberTable.jsx
- src/components/EPRians-admin/MemberTable.style.js
- src/components/EPRians-admin/TableRow.jsx
- src/components/EPRians/Card.jsx
- src/components/EPRians/Dropdown.jsx
- src/components/EPRians/ViewMoreButton.jsx
- src/components/common/CommonButtons/CommonButtons.jsx
- src/components/common/CommonButtons/CommonButtons.style.js
- src/components/common/UploadComponent/UploadComponent.jsx
- src/pages/Admin/Eprians/EPRiansPage.jsx
- src/pages/EPRians/EPRiansPage.jsx
- src/pages/EPRians/EPRiansPage.style.js
- src/pages/Joinus/JoinusPage.jsx
- 이미지 태그 alt 작성
- join us 페이지 타임라인 모바일 버전 애니메이션 제외
- EPRians 페이지 view more 버튼 애니메이션 속도 조정
> EPRians, Join us 페이지 오류를 수정한다.

- src/pages/Main/MainPage.style.js
- 750px-1280px 구간에서 UI가 깨지는것을 수정한다. 
> UI 에러를 수정한다.

- src/components/common/NavigationBar/NavigatonBar.jsx
- src/components/common/NavigationBar/NavigatonBar.style.js
- 모바일 버전의 내비개이션바의 배경 색을 지정
- 메뉴바가 열렸을 때 배경색을 black으로 수정
> 내비게이션바의 배경 색을 수정한다.

- src/assets/AboutPage/left.svg
- src/pages/About/AboutPage.style.js
- src/pages/Admin/ClassInfo/ClassInfoMainPage.jsx
- src/pages/Admin/ClassInfo/ClassInfoPage.jsx
> About, Class_info 페이지의 에러 사항을 수정한다

- src/components/EPRians-admin/TableRow.jsx
- src/components/EPRians/Dropdown.jsx
- src/components/EPRians/ViewMoreButton.jsx
- src/components/EPRians/ViewMoreButton.style.js
- src/components/common/CommonButtons/CommonButtons.jsx
- src/pages/Admin/Eprians/EPRiansPage.jsx
- src/pages/Admin/Recruitment/RecruitmentPage.jsx
- src/pages/EPRians/EPRiansPage.jsx
- src/pages/EPRians/EPRiansPage.style.js
- src/pages/Joinus/JoinusPage.jsx
- src/pages/Joinus/JoinusPage.style.js
- 디자인 QA 수정사항 반영
1. 페이지 배경이미지 뷰포트 너비에 맞춰 확대
2. 모바일 멤버카드 너비에 따라 반응형으로 열 생성
3. 모바일 멤버카드 가나다순 정렬
4. 모바일 Alumni 4명 이하일 때 더보기 버튼 숨김
5. 모바일 기업 카드 크기 수정
6. 모바일 Join us 타임라인 마우스 휠로 가로 스크롤 기능 추가
7. 모바일 Join us 배경 그래픽 추가
8. 어드민 Recruitment 포스터와 파일 비어있을 시 저장 제한
9. 어드민 EPRians 멤버 행 삭제 로직 수정
10. 어드민 EPRians 멤버 테이블/멤버 행 삭제 시 확인 문구 추가
11. 어드민 EPRians 기수 텍스트 변경 시 저장 버튼 활성화
12. 어드민 EPRians 브랜드 카드 화면 재렌더링될때마다 변경사항 리셋
> EPRians, Join us 페이지에 디자인 QA를 반영한다.

- src/components/ClassInfo-admin/CardComponent.jsx
- src/components/Main/Greetings.style.js
- src/pages/Main/MainPage.jsx
- src/pages/Main/MainPage.style.js
- 배경사진 꽉차도록 수정
- 소개글 텍스트 크기 수정
- 그리팅 카드 디자인 수정
- 저장 후 버튼 비활성화
- 삭제시 삭제 재확인 문구 '삭제하시겠습니까?' 추가
> Main과 ClassInfo 뒷페이지에 디자인 QA 요구사항을 반영한다. 

- netlify.toml
- src/api/project.js
- src/components/activities-admin/AwardStatistics.jsx
- src/components/activities-admin/CorporateProject.jsx
- src/components/activities-admin/ProjectItem.jsx
- src/components/activities-admin/ProjectList.jsx
- src/components/activities-admin/UploadItem.jsx
- src/components/activities/Carousel.jsx
- src/components/activities/Carousel.style.js
- src/components/activities/CorporateCard.jsx
- src/components/activities/CorporateCard.style.js
- src/components/common/NavigationBar/NavigatonBar.jsx
- src/components/common/NavigationBar/NavigatonBar.style.js
- src/hooks/useHorizontalScroll.js
- src/hooks/useScrollFadeIn.js
- src/pages/About/AboutPage.jsx
- src/pages/About/AboutPage.style.js
- src/pages/Activity/ActivityPage.jsx
- src/pages/Activity/ActivityPage.style.js
애니메이션 속도, activities 페이지, admin-activities 페이지에 디자인 QA를 반영한다.
- 배경 사진 너비 꽉 차도록 수정
- 애니메이션 속도 0.2s 느리게
- admin-activities 저장/삭제 시 모달 창 확실하게 뜨도록 수정
- 단어 수정
- 어드민 네비바 수정
- activities 페이지 모바일 뷰 캐러셀 -> 스크롤로 수정
> 애니메이션 속도, activities 페이지, admin-activities 페이지에 디자인 QA를 반영한다.

- src/components/activities/Carousel.jsx
- src/components/common/NavigationBar/NavigatonBar.style.js
- src/pages/Contact/ContactPage.jsx
- src/pages/EPRians/EPRiansPage.jsx
- src/pages/Joinus/JoinusPage.jsx
디자인 QA 반영한 2차 배포를 위해 점검한다.
- 네비바 너비 수정
- 네비바 색상 오류 수정
- useHorizontalScroll 적용
> 디자인 QA 반영한 2차 배포를 위해 점검한다.

- src/components/activities/Carousel.jsx
액티비티 페이지 캐러셀 데스크탑 -> 모바일 변경 시 스크롤 안 됨 수정
> 스크롤 오류를 수정한다.

- src/components/activities/Carousel.style.js
> 모바일 캐러셀 너비 오류를 수정한다.

- src/hooks/useHorizontalScroll.js
- src/pages/Joinus/JoinusPage.jsx
- Joinus 페이지 가로스크롤 마우스, 터치패드 둘 다 가능하게 수정
> 🐛 Joinus 가로스크롤 수정

- netlify.toml
- src/components/activities-admin/CorporateProject.jsx
- src/pages/Admin/Eprians/EPRiansPage.jsx
- src/styles/global.css
admin corporate-logo 부분 사진 비율 삭제를 한다.
디자인 QA 반영 수정
> admin corporate-logo 부분 사진 비율 삭제를 한다.

- src/pages/EPRians/EPRiansPage.jsx
- src/pages/EPRians/EPRiansPage.style.js
EPRians 페이지 Alumni 부분 배경색을 흰색으로 수정한다.
> EPRians 페이지 Alumni 부분 배경색을 흰색으로 수정한다.

- src/components/activities/Carousel.jsx
- src/components/activities/Carousel.style.js
- src/components/activities/CorporateCard.jsx
- src/components/activities/CorporateCard.style.js
- src/hooks/useHorizontalScroll.js
캐러셀 컴포넌트에 필요한 변수 계산 파일을 한 군데로 모음
> 캐러셀 코드 개선을 한다.

- public/index.html
> index.html meta 태그를 추가한다.

- src/components/Joinus/ProcessBox.style.js
- src/pages/Joinus/JoinusPage.jsx
- src/pages/Joinus/JoinusPage.style.js
- Joinus 페이지 모바일 버전 디자인을 수정한다.
> Joinus 페이지 모바일 버전 디자인을 수정한다.
